#!/bin/bash

# http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
lang="en_US"
[ ! -z "$2" ] && { lang="$1"; echo "Lang set $lang"; shift; }
mplayer "http://translate.google.com/translate_tts?tl=$lang&q=$1"
