#!/bin/bash

# http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
lang="en_US"
[ "$1" == "-l" ] && { lang="$2"; echo "Lang set $lang"; shift; shift; }
words=$@
mplayer "http://translate.google.com/translate_tts?tl=$lang&q=$words"
